apiVersion: apps/v1
kind: Deployment
metadata:
  name: coding-assesment-tool
  namespace: engines
  labels:
    app: coding-assesment-tool
spec:
  selector:
    matchLabels:
      app: coding-assesment-tool
      tier: web
  template:
    metadata:
      labels:
        app: coding-assesment-tool
        tier: web
    spec:
      containers:
      - name: coding-assesment-tool
        image: 938552122815.dkr.ecr.eu-west-1.amazonaws.com/coding-assesment-tool:dev
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
      nodeSelector:
        app: others
