apiVersion: v1
kind: Service
metadata:
  name: coding-assesment-tool
  namespace: engines-test
  labels:
    app: coding-assesment-tool
spec:
  type: NodePort
  selector:
    app: coding-assesment-tool
    tier: web
  ports:
  - port: 5000
    targetPort: 5000
